<a href="https://colab.research.google.com/github/ProfDoeg/Colegio_Invisible/blob/main/12_cuaderno.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#! rm Colegio_Invisible -r

In [1]:
! pip install Pillow
! git clone https://github.com/ProfDoeg/Colegio_Invisible.git


Cloning into 'Colegio_Invisible'...
remote: Enumerating objects: 999, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 999 (delta 3), reused 0 (delta 0), pack-reused 990
Receiving objects: 100% (999/999), 67.40 MiB | 35.71 MiB/s, done.
Resolving deltas: 100% (684/684), done.


for an image...there are pixels

each pixel has 3,4 values (Red Green Blue and sometime Alpha)

those numbers are...1 byte...0 to 255

In [2]:
from PIL import Image
import numpy as np

In [ ]:
64*8

512

what can we put into blockchain...
Op_Return
80 bytes and we will use 64 bytes for image data

each byte is made up of 8 binary values 1/0 called bits

64 bytes = 64*8...512 bits

We want to put image in single block

PROPOSAL:

16x16 image = 256 pixels

only get to use 2 bits per pixel

- 0,0  0 
- 0,1  64
- 1,0  128
- 1,1  192

1 byte [ , , , , , , , ]

1 byte can tell us color of 4 pixels
each one taking up 2 bits

In [ ]:
""

In [ ]:
!ls Colegio_Invisible/img

Apollo_Slays_Python_1853.jpeg  colegio_invisible.jpeg  rum_1.jpeg
asymmetric.png		       hg_cry.jpeg	       rum_2.jpeg
bab_crop.jpeg		       hg_drop.jpeg	       rum_3.jpeg
barb_1.jpeg		       hg_hide.jpeg	       rum_4.jpeg
barb_2.jpeg		       hg_house.jpeg	       rum_5.jpeg
barb_3.jpeg		       hg_invite.jpeg	       rum_6.jpeg
barb_4.jpeg		       hg_rough.png	       rum_7.jpeg
barb_5.jpeg		       hg_xmas.jpeg	       rump_final.jpeg
barb_6.jpeg		       prv_pub_addr.png        signature.png
barb_7.jpeg		       PubKeyToAddr.png        stego.png
clavis.jpeg		       rum_0.jpeg	       symmetric.png


In [3]:
stego_image=Image.open('Colegio_Invisible/img/stego.png')
stego_image=stego_image.resize((16,16))
stego_image

In [ ]:
type(stego_image)

PIL.Image.Image

In [4]:
stego_array = np.array(stego_image)
stego_array

array([[[179, 131, 173, 255],
        [191, 152, 184, 255],
        [207, 172, 201, 255],
        ...,
        [245, 225, 187, 255],
        [233, 215, 197, 255],
        [228, 208, 229, 255]],

       [[172, 140, 174, 255],
        [182, 146, 179, 255],
        [181, 149, 179, 255],
        ...,
        [214, 197,  94, 255],
        [234, 214, 137, 255],
        [227, 208, 209, 255]],

       [[101, 112, 121, 255],
        [124, 119, 139, 255],
        [141, 105, 100, 255],
        ...,
        [105, 124,  87, 255],
        [130, 140,  98, 255],
        [151, 158, 141, 255]],

       ...,

       [[ 85,  65,  92, 255],
        [125,  92,  81, 255],
        [221, 154,  38, 255],
        ...,
        [113,  89, 107, 255],
        [102,  85, 101, 255],
        [ 93,  81,  97, 255]],

       [[111,  79,  96, 255],
        [164, 118,  77, 255],
        [194, 143,  63, 255],
        ...,
        [127,  96, 112, 255],
        [135, 100, 111, 255],
        [110,  96, 106, 255]],

       [[ 99

**`uint8`** stands for unsigned 8-bit integer
- 8 binary 1/0 values
- that is one byte
- a number from 0-255
- two hex values like ff

In [5]:
stego_array.dtype

dtype('uint8')

In [6]:
stego_array.shape

(16, 16, 4)

In [7]:
stego_array[:,:,:3]

array([[[179, 131, 173],
        [191, 152, 184],
        [207, 172, 201],
        [220, 191, 217],
        [216, 191, 212],
        [210, 185, 207],
        [209, 180, 206],
        [215, 185, 210],
        [226, 202, 227],
        [220, 195, 219],
        [225, 200, 223],
        [224, 206, 225],
        [238, 217, 214],
        [245, 225, 187],
        [233, 215, 197],
        [228, 208, 229]],

       [[172, 140, 174],
        [182, 146, 179],
        [181, 149, 179],
        [187, 166, 192],
        [206, 155, 162],
        [192, 147, 155],
        [184, 148, 160],
        [198, 146, 144],
        [195, 174, 199],
        [198, 175, 190],
        [191, 173, 198],
        [215, 195, 190],
        [205, 189, 126],
        [214, 197,  94],
        [234, 214, 137],
        [227, 208, 209]],

       [[101, 112, 121],
        [124, 119, 139],
        [141, 105, 100],
        [102,  97, 104],
        [174,  99,  78],
        [160,  87,  68],
        [159,  93,  74],
        [180, 106,  8

In [8]:
stego_array_grey=stego_array[:,:,:3].mean(axis=2).astype('uint8')
stego_array_grey.shape,stego_array_grey.dtype

((16, 16), dtype('uint8'))

In [9]:
stego_array_grey

array([[161, 175, 193, 209, 206, 200, 198, 203, 218, 211, 216, 218, 223,
        219, 215, 221],
       [162, 169, 169, 181, 174, 164, 164, 162, 189, 187, 187, 200, 173,
        168, 195, 214],
       [111, 127, 115, 101, 117, 105, 108, 122, 117, 118, 106, 132, 125,
        105, 122, 150],
       [ 89,  89, 103,  87,  96,  91,  99, 108,  97,  99,  77,  78,  70,
         60,  61,  72],
       [ 79,  68,  79,  85,  77,  75,  82,  85,  76,  75, 101,  82,  70,
         75,  68,  65],
       [ 98,  92,  80,  92, 106, 120, 147, 145, 120,  92, 101,  96,  84,
         85, 103,  95],
       [ 71,  81,  84, 128, 148, 143, 165, 167, 154, 145, 104,  83,  89,
         89, 136, 104],
       [104, 121, 126, 151, 149, 153, 168, 163, 151, 151, 148, 112, 107,
        137, 149,  80],
       [150, 163, 131, 150, 153, 156, 164, 163, 153, 151, 155, 153, 154,
        157,  97,  86],
       [137, 137, 156, 160, 150, 154, 164, 160, 157, 156, 159, 160, 132,
         89,  85,  98],
       [146, 146, 173, 168, 15

In [10]:
stego_image_grey = Image.fromarray(stego_array_grey)
stego_image_grey

In [ ]:
print(150%64)
print(150-22)

22
128


In [11]:
stego_array_grey_2b=stego_array_grey-(stego_array_grey%64)
stego_array_grey_2b

array([[128, 128, 192, 192, 192, 192, 192, 192, 192, 192, 192, 192, 192,
        192, 192, 192],
       [128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 192, 128,
        128, 192, 192],
       [ 64,  64,  64,  64,  64,  64,  64,  64,  64,  64,  64, 128,  64,
         64,  64, 128],
       [ 64,  64,  64,  64,  64,  64,  64,  64,  64,  64,  64,  64,  64,
          0,   0,  64],
       [ 64,  64,  64,  64,  64,  64,  64,  64,  64,  64,  64,  64,  64,
         64,  64,  64],
       [ 64,  64,  64,  64,  64,  64, 128, 128,  64,  64,  64,  64,  64,
         64,  64,  64],
       [ 64,  64,  64, 128, 128, 128, 128, 128, 128, 128,  64,  64,  64,
         64, 128,  64],
       [ 64,  64,  64, 128, 128, 128, 128, 128, 128, 128, 128,  64,  64,
        128, 128,  64],
       [128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128,
        128,  64,  64],
       [128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128,
         64,  64,  64],
       [128, 128, 128, 128, 12

In [12]:
stego_image_grey_2b = Image.fromarray(stego_array_grey_2b)
stego_image_grey_2b

In [13]:
def int_2_bit_array(num):
    bin_str=bin(num)
    bit_list=[int(bit) for bit in bin_str[2:]]
    bit_list=[0]*(8-len(bit_list))+bit_list
    bit_array=np.array(bit_list,dtype='uint8')
    return bit_array

In [16]:
int_2_bit_array(0)

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8)

In [17]:
int_2_bit_array(64)

array([0, 1, 0, 0, 0, 0, 0, 0], dtype=uint8)

In [ ]:
int_2_bit_array(128)

array([1, 0, 0, 0, 0, 0, 0, 0], dtype=uint8)

In [ ]:
int_2_bit_array(192)

array([1, 1, 0, 0, 0, 0, 0, 0], dtype=uint8)

In [24]:
int_2_bit_array(153).shape

(8,)

In [ ]:
int_2_bit_array(stego_array_grey_2b)

TypeError: ignored

In [22]:
np.vectorize(int_2_bit_array)

Goal:

- take image of 256 bytes and reduce each byte to 2 bit in form of 2 element array
- turn that all into 512 bits
- turn 512 bits into 64 bytes

In [36]:
data=np.array([int_2_bit_array(elem)[:2] for elem in stego_array_grey_2b.reshape(-1)]).reshape(-1)
data

array([1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,

In [40]:
bin_array=data.reshape(-1,8)
bin_array

array([[1, 0, 1, 0, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 1],
       [1, 0, 1, 0, 1, 1, 1, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 1, 0],
       [0, 1, 0, 1, 0, 1, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 0, 0, 0, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 0, 1, 0, 1],
       [0, 1, 0, 1, 1, 0, 0, 1],
       [0, 1, 0, 1, 0, 1, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1,

In [52]:
def bit8array2byte(bin_array):
  return int(''.join([str(i) for i in bin_array]),2).to_bytes(1,'big')

In [55]:
def bit8arrays2bytestring(A):
  return  b''.join([bit8array2byte( bin8 ) for bin8 in A])

In [60]:
len(bit8arrays2bytestring(bin_array))

64